spring:
  redis:
    node: redis://localhost:6370, redis://localhost:6371, redis://localhost:6372, redis://localhost:6380, redis://localhost:6381, redis://localhost:6382
    lettuce-node: localhost:6370, localhost:6371, localhost:6372, localhost:6380, localhost:6381, localhost:6382